package cl.model.pojos;
// Generated 10-19-2014 07:15:35 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Reclamo generated by hbm2java
 */
public class Reclamo  implements java.io.Serializable {


     private BigDecimal identificador;
     private Usuario usuario;
     private Serializable fecha;
     private String usuario_1;
     private String titulo;
     private String cuerpo;
     private String sector;
     private String lugarreclamado;

    public Reclamo() {
    }

	
    public Reclamo(BigDecimal identificador, Serializable fecha, String usuario_1, String cuerpo, String sector, String lugarreclamado) {
        this.identificador = identificador;
        this.fecha = fecha;
        this.usuario_1 = usuario_1;
        this.cuerpo = cuerpo;
        this.sector = sector;
        this.lugarreclamado = lugarreclamado;
    }
    public Reclamo(BigDecimal identificador, Usuario usuario, Serializable fecha, String usuario_1, String titulo, String cuerpo, String sector, String lugarreclamado) {
       this.identificador = identificador;
       this.usuario = usuario;
       this.fecha = fecha;
       this.usuario_1 = usuario_1;
       this.titulo = titulo;
       this.cuerpo = cuerpo;
       this.sector = sector;
       this.lugarreclamado = lugarreclamado;
    }
   
    public BigDecimal getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(BigDecimal identificador) {
        this.identificador = identificador;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Serializable getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Serializable fecha) {
        this.fecha = fecha;
    }
    public String getUsuario_1() {
        return this.usuario_1;
    }
    
    public void setUsuario_1(String usuario_1) {
        this.usuario_1 = usuario_1;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getCuerpo() {
        return this.cuerpo;
    }
    
    public void setCuerpo(String cuerpo) {
        this.cuerpo = cuerpo;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    public String getLugarreclamado() {
        return this.lugarreclamado;
    }
    
    public void setLugarreclamado(String lugarreclamado) {
        this.lugarreclamado = lugarreclamado;
    }




}


